// <auto-generated />
namespace Miki.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sqlservertopostgres : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sqlservertopostgres));
        
        string IMigrationMetadata.Id
        {
            get { return "201708030141215_sqlserver-to-postgres"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
