// <auto-generated />
namespace Miki.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addpastascore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addpastascore));
        
        string IMigrationMetadata.Id
        {
            get { return "201711202216564_add-pasta-score"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
