// <auto-generated />
namespace Miki.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddPinnedBadges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPinnedBadges));
        
        string IMigrationMetadata.Id
        {
            get { return "201711041525517_Add-Pinned-Badges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
