// <auto-generated />
namespace Miki.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addlevelrolerequiredrole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addlevelrolerequiredrole));
        
        string IMigrationMetadata.Id
        {
            get { return "201711160131165_add-levelrole-requiredrole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
