//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miki.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class bg_BG {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal bg_BG() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Miki.Languages.bg-BG", typeof(bg_BG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нещо се обърка !.
        /// </summary>
        internal static string miki_error_message_generic {
            get {
                return ResourceManager.GetString("miki_error_message_generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мики има проблем с заявката ти в кода й.Ще ви пратим инструкции какво да правите по Личните съобщения.
        /// </summary>
        internal static string miki_errors_enabled_message {
            get {
                return ResourceManager.GetString("miki_errors_enabled_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} твоят глобален профил.
        /// </summary>
        internal static string miki_global_profile_user_header {
            get {
                return ResourceManager.GetString("miki_global_profile_user_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравей ! Аз съм **Miki**! Използвай &apos;&gt;help&apos; за да провериш какво мога да правя! :notes:.
        /// </summary>
        internal static string miki_join_message {
            get {
                return ResourceManager.GetString("miki_join_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} твоят локален профил .
        /// </summary>
        internal static string miki_local_profile_user_header {
            get {
                return ResourceManager.GetString("miki_local_profile_user_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нямаш достатъчно мекоси !.
        /// </summary>
        internal static string miki_mekos_insufficient {
            get {
                return ResourceManager.GetString("miki_mekos_insufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Съобщението ти за посрещане ти беше естрито..
        /// </summary>
        internal static string miki_module_eventmessages_delete_guildjoin {
            get {
                return ResourceManager.GetString("miki_module_eventmessages_delete_guildjoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Новото ти съобщение при посрещане е сложено на: `{0}`.
        /// </summary>
        internal static string miki_module_eventmessages_set_guildjoin {
            get {
                return ResourceManager.GetString("miki_module_eventmessages_set_guildjoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не му разчитай..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_negative_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_negative_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моят отговор е не..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_negative_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_negative_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моите източници казват не..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_negative_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_negative_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Външния вид не е добре..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_negative_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_negative_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доста съмнително..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_negative_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_negative_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отговорът ти не се разбира , опитай отново..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_neutral_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_neutral_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попитай отново по-късно..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_neutral_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_neutral_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По-добре да не ти казвам сега..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_neutral_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_neutral_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не мога да преценя сега..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_neutral_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_neutral_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Концентрирай се и попитай отново..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_neutral_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_neutral_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурно е..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Това определено е така..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без съмнение..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да , определено..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Може би, може да му вярваш..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Най-вероятно..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_6 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Външния вид е добър..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_7 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_8 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следите сочат към да..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_9 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Долната част на устните ти..
        /// </summary>
        internal static string miki_module_fun_compliment_body_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to специалните ъгли които лактите ти правят.
        /// </summary>
        internal static string miki_module_fun_compliment_body_10 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to трапчинките на бузите ти.
        /// </summary>
        internal static string miki_module_fun_compliment_body_11 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to твоята гладка коса.
        /// </summary>
        internal static string miki_module_fun_compliment_body_12 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to най-малкия пръст на левия ти крак.
        /// </summary>
        internal static string miki_module_fun_compliment_body_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to най-малкия пръст на десния ти крак.
        /// </summary>
        internal static string miki_module_fun_compliment_body_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to втората мигла на лявото ти око.
        /// </summary>
        internal static string miki_module_fun_compliment_body_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to долната част на брадичката ти.
        /// </summary>
        internal static string miki_module_fun_compliment_body_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to зловещия пръст на лявата ти ръка.
        /// </summary>
        internal static string miki_module_fun_compliment_body_6 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сладката ти усмивка.
        /// </summary>
        internal static string miki_module_fun_compliment_body_7 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to твоите ослепителни очи.
        /// </summary>
        internal static string miki_module_fun_compliment_body_8 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to зловещия пръст на дясната ти ръка.
        /// </summary>
        internal static string miki_module_fun_compliment_body_9 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аз харесвам.
        /// </summary>
        internal static string miki_module_fun_compliment_prefix_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_prefix_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аз обичам.
        /// </summary>
        internal static string miki_module_fun_compliment_prefix_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_prefix_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аз уважавам.
        /// </summary>
        internal static string miki_module_fun_compliment_prefix_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_prefix_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аз наистина се наслъждавам.
        /// </summary>
        internal static string miki_module_fun_compliment_prefix_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_prefix_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поради някаква причина , аз харесвам.
        /// </summary>
        internal static string miki_module_fun_compliment_prefix_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_prefix_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to много..
        /// </summary>
        internal static string miki_module_fun_compliment_suffix_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_suffix_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to малко..
        /// </summary>
        internal static string miki_module_fun_compliment_suffix_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_suffix_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to доста..
        /// </summary>
        internal static string miki_module_fun_compliment_suffix_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_suffix_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to много, това странно ли е?.
        /// </summary>
        internal static string miki_module_fun_compliment_suffix_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_suffix_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Аз избирам `{1}`.
        /// </summary>
        internal static string miki_module_fun_pick {
            get {
                return ResourceManager.GetString("miki_module_fun_pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нямам нищо от което да избирам! :( Използвай запетайка (,) за да разделиш изборите.
        /// </summary>
        internal static string miki_module_fun_pick_no_arg {
            get {
                return ResourceManager.GetString("miki_module_fun_pick_no_arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не мога да повярвам че ме уволниха от фабриката са календари. Всичко което направих беше да си взема почивен ден.
        /// </summary>
        internal static string miki_module_fun_pun_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Когато съм гола в банята , душа обикновенно се пуска..
        /// </summary>
        internal static string miki_module_fun_pun_10 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крадци влязоха в къщата ми и откраднаха всичко освен моят сапун , шампоан , хавлии и дезодорант. Мръсници ..
        /// </summary>
        internal static string miki_module_fun_pun_11 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каква беше паролата на Forrest Gump?&apos;1forrest1&apos;.
        /// </summary>
        internal static string miki_module_fun_pun_12 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Първата ми работа беше в фабрика за портокален сок , но ме изцедиха - не можех да се концентрирам.
        /// </summary>
        internal static string miki_module_fun_pun_13 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аз съм на морска диета.Всеки път когато видя храна , я изяждам.
        /// </summary>
        internal static string miki_module_fun_pun_14 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Искам да направя шега за Натрий , но Неее....
        /// </summary>
        internal static string miki_module_fun_pun_15 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защо ученият сложил катинар на вратата си ? За да спечели Но-белова награда.
        /// </summary>
        internal static string miki_module_fun_pun_16 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_17 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да правиш секс в асансьор е грешно на много нива .
        /// </summary>
        internal static string miki_module_fun_pun_18 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исках да му дам гаден поглед но той вече си имаше един.
        /// </summary>
        internal static string miki_module_fun_pun_19 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как избягах от Ирак? Иран..
        /// </summary>
        internal static string miki_module_fun_pun_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книга ми падна на главата. Имам само рафта да виня.
        /// </summary>
        internal static string miki_module_fun_pun_20 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какво използват затворниците за да се чуват? Килийни телефони.
        /// </summary>
        internal static string miki_module_fun_pun_21 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учителят ми по математика ме нарече среден.Колко подло!.
        /// </summary>
        internal static string miki_module_fun_pun_22 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не съм фотограф на мога да си ни представя заедно.
        /// </summary>
        internal static string miki_module_fun_pun_23 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как мога да намеря сляп човек в нудистка колония? Не е трудно..
        /// </summary>
        internal static string miki_module_fun_pun_24 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Атеизмът е организация , която няма пророк..
        /// </summary>
        internal static string miki_module_fun_pun_25 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как наричаме човек страхуващ се от Дядо Коледа ? Неискащ подръци.
        /// </summary>
        internal static string miki_module_fun_pun_26 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дупка беше направена в нудистка стена.Полицията гледа през нея..
        /// </summary>
        internal static string miki_module_fun_pun_27 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кой е любимия ден на кокошките ? Деня на благодарността.
        /// </summary>
        internal static string miki_module_fun_pun_28 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Във връзка с големите студове и снегове, Европейският парламент изпратил официално писмо до Чък Норис с молба да провери да не би да е забравил вратата на хладилника си отворена..
        /// </summary>
        internal static string miki_module_fun_pun_29 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ще кажа шега по химия но няма да получа реакция..
        /// </summary>
        internal static string miki_module_fun_pun_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чухте ли за болния италиянски шеф.Той pastaaway.
        /// </summary>
        internal static string miki_module_fun_pun_30 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чък Норис участва във всички серии на &quot;Междузвездни войни&quot;. Той играл Силата..
        /// </summary>
        internal static string miki_module_fun_pun_31 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Никога не обсъждай безкрайността с математик , могат да говорят вечно.
        /// </summary>
        internal static string miki_module_fun_pun_32 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Когато Чък Норис пресича, колите се оглеждат.
        /// </summary>
        internal static string miki_module_fun_pun_33 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какво казало сушито на пчелата ? Уасабии..
        /// </summary>
        internal static string miki_module_fun_pun_34 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вярвай на атомите , правят всичко.
        /// </summary>
        internal static string miki_module_fun_pun_35 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пенсионер към личния си доктор: 
        ///- Има слух, че при вас в поликлиниката ще давате безплатно лекарства! 
        ///- Проблеми със слуха - това е за съседния кабинет!.
        /// </summary>
        internal static string miki_module_fun_pun_36 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Най-страшният сън на катаджията: всички шофьори спазват правилника за движение по пътищата..
        /// </summary>
        internal static string miki_module_fun_pun_37 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ако получите от мен съобщение с текст - &quot;Не пия Бира&quot;, значи е Вирус....
        /// </summary>
        internal static string miki_module_fun_pun_38 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Докторе от какво е болна жена ми? 
        ///- Или е СПИН или Алцхаймер. 
        ///- Какво да правя? 
        ///- Остави я на 10 км. от къщи, ако се прибере, не я е*и..
        /// </summary>
        internal static string miki_module_fun_pun_39 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Три месеца будистките монаси се ровеха в най-тайните и свещени книги, но така и не успяха да открият нещо, което все още не е цитирано във Фейсбук..
        /// </summary>
        internal static string miki_module_fun_pun_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to – Ще се качиш ли да пием по едно вкъщи? 
        ///– Не. 
        ///– Не мисли, че каня всяка срещната! 
        ///– Е, то и аз не отказвам на всеки..
        /// </summary>
        internal static string miki_module_fun_pun_40 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какви са диодите в Iphone? 
        ///Отговор: Idiod
        ///
        ///.
        /// </summary>
        internal static string miki_module_fun_pun_41 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Искате нов монитор? 
        ///Изтрийте тук ▒▒▒▒▒▒▒▒▒▒▒▒▒ с ключ или стотинка!.
        /// </summary>
        internal static string miki_module_fun_pun_42 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ако прекалите с лекарствата за умствено разстройство може да получите умствен запек.
        ///
        ///.
        /// </summary>
        internal static string miki_module_fun_pun_43 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Нова Броудкастинг Груп стартира онлайн платформа за проверка на достоверността на новините&quot;. 
        ///Само един въпрос: На кого и колко трябва да платим?.
        /// </summary>
        internal static string miki_module_fun_pun_44 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тази година Ман Сити похарчиха повече за отбраната си отколкото България..
        /// </summary>
        internal static string miki_module_fun_pun_45 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Защо само Сатурн има пръстени? 
        ///- Защото само той се е оженил..
        /// </summary>
        internal static string miki_module_fun_pun_46 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Той: Сега разбрах защо ти викат &quot;Коте&quot;. 
        ///Тя: Защо? 
        ///Той: Заради мустаците!.
        /// </summary>
        internal static string miki_module_fun_pun_47 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Най-доброто лекарство против махмурлук било бирата. Глупости на таркалета! Вече 10та бира пия и все по-зле ми става!.
        /// </summary>
        internal static string miki_module_fun_pun_48 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Каква е това &quot;мицеларна вода&quot;? 
        ///- Как каква - от мицел..
        /// </summary>
        internal static string miki_module_fun_pun_49 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какво е изобразено на знамето на Канада, та чак е прикрито с листо?.
        /// </summary>
        internal static string miki_module_fun_pun_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_50 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_51 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_52 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_6 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_7 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_8 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_9 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_9", resourceCulture);
            }
        }
    }
}
