//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miki.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class da_DK {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal da_DK() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Miki.Languages.da-DK", typeof(da_DK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_command_description_8ball {
            get {
                return ResourceManager.GetString("miki_command_description_8ball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_command_description_pasta {
            get {
                return ResourceManager.GetString("miki_command_description_pasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_command_usage_8ball {
            get {
                return ResourceManager.GetString("miki_command_usage_8ball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_command_usage_pasta {
            get {
                return ResourceManager.GetString("miki_command_usage_pasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noget gik galt!.
        /// </summary>
        internal static string miki_error_message_generic {
            get {
                return ResourceManager.GetString("miki_error_message_generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miki stødte på et problem i kørslen af anmodning. Vi vil sende dig en log og instruktioner via. DM.
        /// </summary>
        internal static string miki_errors_enabled_message {
            get {
                return ResourceManager.GetString("miki_errors_enabled_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s globale profil.
        /// </summary>
        internal static string miki_global_profile_user_header {
            get {
                return ResourceManager.GetString("miki_global_profile_user_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hej, **Miki**! til tjeneste!
        ///Skrive **&gt;help** for at tjekke hvad jeg kan gøre! :notes:.
        /// </summary>
        internal static string miki_join_message {
            get {
                return ResourceManager.GetString("miki_join_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s lokale profil.
        /// </summary>
        internal static string miki_local_profile_user_header {
            get {
                return ResourceManager.GetString("miki_local_profile_user_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har en utilstrækkelig mængde af mekos..
        /// </summary>
        internal static string miki_mekos_insufficient {
            get {
                return ResourceManager.GetString("miki_mekos_insufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_admin_enabled_module {
            get {
                return ResourceManager.GetString("miki_module_admin_enabled_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Velkommen beskeden, blev slettet..
        /// </summary>
        internal static string miki_module_eventmessages_delete_guildjoin {
            get {
                return ResourceManager.GetString("miki_module_eventmessages_delete_guildjoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Ny Velkommen beskeden: `{0}`.
        /// </summary>
        internal static string miki_module_eventmessages_set_guildjoin {
            get {
                return ResourceManager.GetString("miki_module_eventmessages_set_guildjoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lad være med at stole på det..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_negative_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_negative_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit svar er, nej!.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_negative_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_negative_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine kilder siger nej....
        /// </summary>
        internal static string miki_module_fun_8ball_answer_negative_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_negative_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svaret er knap så godt..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_negative_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_negative_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stærkt tvivlsomt..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_negative_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_negative_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke tyde dit svar. Prøv igen..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_neutral_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_neutral_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spørg igen senere!.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_neutral_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_neutral_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeg burde ikke give svaret nu....
        /// </summary>
        internal static string miki_module_fun_8ball_answer_neutral_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_neutral_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke forudsige dit svar, lige nu..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_neutral_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_neutral_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koncentrer og spørg igen..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_neutral_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_neutral_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det er uden tvivl.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skæbnen har valgt det sådanne..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uden tvivl.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja, helt sikkert!.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja, det kan du stole på..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Højst sandsynligt.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_6 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultatet ser godt ud!.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_7 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_8 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt tyder på det er ja..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_9 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_8ball_result {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to din underlæbe..
        /// </summary>
        internal static string miki_module_fun_compliment_body_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alle de specielle vinkler dine albuer laver..
        /// </summary>
        internal static string miki_module_fun_compliment_body_10 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dine smilehuller..
        /// </summary>
        internal static string miki_module_fun_compliment_body_11 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dit bløde hår..
        /// </summary>
        internal static string miki_module_fun_compliment_body_12 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to den mindste tå på din venstre fod..
        /// </summary>
        internal static string miki_module_fun_compliment_body_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to den mindste tå på din højre fod..
        /// </summary>
        internal static string miki_module_fun_compliment_body_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to den anden øjenvippe fra dit venstre øje..
        /// </summary>
        internal static string miki_module_fun_compliment_body_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to den nedre del af din hage..
        /// </summary>
        internal static string miki_module_fun_compliment_body_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dine uhyggelige fingere på din venstre hånd..
        /// </summary>
        internal static string miki_module_fun_compliment_body_6 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dit søde smil..
        /// </summary>
        internal static string miki_module_fun_compliment_body_7 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dine blændende øjne..
        /// </summary>
        internal static string miki_module_fun_compliment_body_8 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dine uhyggelige fingere på din højre hånd..
        /// </summary>
        internal static string miki_module_fun_compliment_body_9 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det fint, det kan jeg lide..
        /// </summary>
        internal static string miki_module_fun_compliment_prefix_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_prefix_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeg elsker.
        /// </summary>
        internal static string miki_module_fun_compliment_prefix_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_prefix_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jeg beundrer.
        /// </summary>
        internal static string miki_module_fun_compliment_prefix_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_prefix_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeg godt lide.
        /// </summary>
        internal static string miki_module_fun_compliment_prefix_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_prefix_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Af en eller anden årsag, så kan jeg godt lide.
        /// </summary>
        internal static string miki_module_fun_compliment_prefix_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_prefix_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meget..
        /// </summary>
        internal static string miki_module_fun_compliment_suffix_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_suffix_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en smule..
        /// </summary>
        internal static string miki_module_fun_compliment_suffix_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_suffix_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en hel del..
        /// </summary>
        internal static string miki_module_fun_compliment_suffix_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_suffix_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meget... Er det mærkeligt?.
        /// </summary>
        internal static string miki_module_fun_compliment_suffix_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_suffix_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_image_error_no_image_found {
            get {
                return ResourceManager.GetString("miki_module_fun_image_error_no_image_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Jeg valgte `{1}`.
        /// </summary>
        internal static string miki_module_fun_pick {
            get {
                return ResourceManager.GetString("miki_module_fun_pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeg har intet at vælge imellem.
        ///Brug komma (,) til at separere valgmulighederne..
        /// </summary>
        internal static string miki_module_fun_pick_no_arg {
            get {
                return ResourceManager.GetString("miki_module_fun_pick_no_arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_10 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_11 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hvad var Forrest Gump&apos;s adgangskode til hans email? &apos;1forrest1&apos;.
        /// </summary>
        internal static string miki_module_fun_pun_12 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit første job var i en appelsinjuice-fabrik, hvor jeg blev fyret. Jeg kunne ikke koncentrere mig..
        /// </summary>
        internal static string miki_module_fun_pun_13 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_14 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeg ville fortælle en vittighed om Natrium men Na....
        /// </summary>
        internal static string miki_module_fun_pun_15 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_16 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_17 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_18 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_19 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_20 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_21 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_22 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_23 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_24 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_25 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_26 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_27 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_28 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_29 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_30 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_31 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_32 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_33 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hvad sagde sushien til honningbien? Wasabi.
        /// </summary>
        internal static string miki_module_fun_pun_34 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeg ville fortælle dine kemikere en vittighed, men jeg ved, at jeg ikke ville få en reaktion..
        /// </summary>
        internal static string miki_module_fun_pun_35 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_36 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_37 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_38 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_39 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_40 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_41 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_42 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_43 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_44 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_45 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_46 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_47 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_48 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_49 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_50 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_51 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_52 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_6 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_7 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_8 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_pun_9 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rullede en **{1}**.
        /// </summary>
        internal static string miki_module_fun_roll_result {
            get {
                return ResourceManager.GetString("miki_module_fun_roll_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Og vinderen af {0} er {1} !.
        /// </summary>
        internal static string miki_module_fun_roulette_winner {
            get {
                return ResourceManager.GetString("miki_module_fun_roulette_winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Og vinderen er {0} !.
        /// </summary>
        internal static string miki_module_fun_roulette_winner_no_arg {
            get {
                return ResourceManager.GetString("miki_module_fun_roulette_winner_no_arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slots.
        /// </summary>
        internal static string miki_module_fun_slots_header {
            get {
                return ResourceManager.GetString("miki_module_fun_slots_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}🔸 er blevet tilføjet din Miki konto..
        /// </summary>
        internal static string miki_module_fun_slots_win_amount {
            get {
                return ResourceManager.GetString("miki_module_fun_slots_win_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du vinder!.
        /// </summary>
        internal static string miki_module_fun_slots_win_header {
            get {
                return ResourceManager.GetString("miki_module_fun_slots_win_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_create_error_already_exist {
            get {
                return ResourceManager.GetString("miki_module_pasta_create_error_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_create_success {
            get {
                return ResourceManager.GetString("miki_module_pasta_create_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_delete_success {
            get {
                return ResourceManager.GetString("miki_module_pasta_delete_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_edit_success {
            get {
                return ResourceManager.GetString("miki_module_pasta_edit_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_error_no_permissions {
            get {
                return ResourceManager.GetString("miki_module_pasta_error_no_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_error_null {
            get {
                return ResourceManager.GetString("miki_module_pasta_error_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_error_search_no_arg {
            get {
                return ResourceManager.GetString("miki_module_pasta_error_search_no_arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_error_search_no_results {
            get {
                return ResourceManager.GetString("miki_module_pasta_error_search_no_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_error_specify {
            get {
                return ResourceManager.GetString("miki_module_pasta_error_specify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_error_specify_check {
            get {
                return ResourceManager.GetString("miki_module_pasta_error_specify_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_error_specify_delete {
            get {
                return ResourceManager.GetString("miki_module_pasta_error_specify_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_error_specify_edit {
            get {
                return ResourceManager.GetString("miki_module_pasta_error_specify_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_error_specify_upvote {
            get {
                return ResourceManager.GetString("miki_module_pasta_error_specify_upvote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_identify_created_by {
            get {
                return ResourceManager.GetString("miki_module_pasta_identify_created_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_identify_date_created {
            get {
                return ResourceManager.GetString("miki_module_pasta_identify_date_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_identify_rating {
            get {
                return ResourceManager.GetString("miki_module_pasta_identify_rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_identify_times_used {
            get {
                return ResourceManager.GetString("miki_module_pasta_identify_times_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_mine_error_null {
            get {
                return ResourceManager.GetString("miki_module_pasta_mine_error_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_mine_header {
            get {
                return ResourceManager.GetString("miki_module_pasta_mine_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_search_error_no_results {
            get {
                return ResourceManager.GetString("miki_module_pasta_search_error_no_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_search_footer {
            get {
                return ResourceManager.GetString("miki_module_pasta_search_footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_search_header {
            get {
                return ResourceManager.GetString("miki_module_pasta_search_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_pasta_vote_success {
            get {
                return ResourceManager.GetString("miki_module_pasta_vote_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_success_message_generic {
            get {
                return ResourceManager.GetString("miki_success_message_generic", resourceCulture);
            }
        }
    }
}
