//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miki.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Miki.Languages.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}** levelled up to level **{1}**!.
        /// </summary>
        internal static string miki_accounts_level_up_content {
            get {
                return ResourceManager.GetString("miki_accounts_level_up_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☀️️ level up!.
        /// </summary>
        internal static string miki_accounts_level_up_header {
            get {
                return ResourceManager.GetString("miki_accounts_level_up_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push your luck by asking Miki specific questions about your life!.
        /// </summary>
        internal static string miki_command_description_8ball {
            get {
                return ResourceManager.GetString("miki_command_description_8ball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you done being married? Divorce today!.
        /// </summary>
        internal static string miki_command_description_divorce {
            get {
                return ResourceManager.GetString("miki_command_description_divorce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows information about the bot and its creator..
        /// </summary>
        internal static string miki_command_description_info {
            get {
                return ResourceManager.GetString("miki_command_description_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out the Miki elites!.
        /// </summary>
        internal static string miki_command_description_leaderboards {
            get {
                return ResourceManager.GetString("miki_command_description_leaderboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and load lines of text..
        /// </summary>
        internal static string miki_command_description_pasta {
            get {
                return ResourceManager.GetString("miki_command_description_pasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your server&apos;s prefix for miki (default: &gt;) to something else.
        /// </summary>
        internal static string miki_command_description_prefix {
            get {
                return ResourceManager.GetString("miki_command_description_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check up on your progress to become a Miki Master!.
        /// </summary>
        internal static string miki_command_description_profile {
            get {
                return ResourceManager.GetString("miki_command_description_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Miki&apos;s ability to send you DM&apos;s!.
        /// </summary>
        internal static string miki_command_description_toggledm {
            get {
                return ResourceManager.GetString("miki_command_description_toggledm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Miki&apos;s ability to send you Error DM&apos;s!.
        /// </summary>
        internal static string miki_command_description_toggleerrors {
            get {
                return ResourceManager.GetString("miki_command_description_toggleerrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Miki&apos;s ability to send non-command messages in this channel!.
        /// </summary>
        internal static string miki_command_description_toggleguildnotifications {
            get {
                return ResourceManager.GetString("miki_command_description_toggleguildnotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;8ball &lt;question&gt;.
        /// </summary>
        internal static string miki_command_usage_8ball {
            get {
                return ResourceManager.GetString("miki_command_usage_8ball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;divorce @user
        ///&gt;divorce user.
        /// </summary>
        internal static string miki_command_usage_divorce {
            get {
                return ResourceManager.GetString("miki_command_usage_divorce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;info.
        /// </summary>
        internal static string miki_command_usage_info {
            get {
                return ResourceManager.GetString("miki_command_usage_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;leaderboards
        ///&gt;leaderboards local
        ///&gt;leaderboards mekos
        ///&gt;leaderboards commands.
        /// </summary>
        internal static string miki_command_usage_leaderboards {
            get {
                return ResourceManager.GetString("miki_command_usage_leaderboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;pasta new &lt;keyword&gt; &lt;content of pasta&gt;
        ///&gt;pasta + &lt;keyword&gt; &lt;content of pasta&gt;
        ///&gt;pasta find &lt;keyword&gt;
        ///&gt;pasta search &lt;keyword&gt;
        ///&gt;pasta edit &lt;keyword&gt; &lt;content to edit&gt;
        ///&gt;pasta change &lt;keyword&gt; &lt;content to edit&gt;
        ///&gt;pasta who &lt;keyword&gt;
        ///&gt;pasta whom &lt;keyword&gt;
        ///&gt;pasta ? &lt;keyword&gt;
        ///&gt;pasta upvote &lt;keyword&gt;
        ///&gt;pasta &lt;3 &lt;keyword&gt;
        ///&gt;pasta love &lt;keyword&gt;
        ///&gt;pasta downvote &lt;keyword&gt;
        ///&gt;pasta &lt;/3 &lt;keyword&gt;
        ///&gt;pasta hate &lt;keyword&gt;.
        /// </summary>
        internal static string miki_command_usage_pasta {
            get {
                return ResourceManager.GetString("miki_command_usage_pasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;prefix ~.
        /// </summary>
        internal static string miki_command_usage_prefix {
            get {
                return ResourceManager.GetString("miki_command_usage_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;profile
        ///&gt;profile &lt;userid&gt;.
        /// </summary>
        internal static string miki_command_usage_profile {
            get {
                return ResourceManager.GetString("miki_command_usage_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;toggledm.
        /// </summary>
        internal static string miki_command_usage_toggledm {
            get {
                return ResourceManager.GetString("miki_command_usage_toggledm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;toggleerrors.
        /// </summary>
        internal static string miki_command_usage_toggleerrors {
            get {
                return ResourceManager.GetString("miki_command_usage_toggleerrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        internal static string miki_error_message_generic {
            get {
                return ResourceManager.GetString("miki_error_message_generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miki has encountered a problem with your request in her code. We will send you a log and instructions through PM..
        /// </summary>
        internal static string miki_errors_enabled_message {
            get {
                return ResourceManager.GetString("miki_errors_enabled_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        internal static string miki_generic_achievements {
            get {
                return ResourceManager.GetString("miki_generic_achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled.
        /// </summary>
        internal static string miki_generic_disabled {
            get {
                return ResourceManager.GetString("miki_generic_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enabled.
        /// </summary>
        internal static string miki_generic_enabled {
            get {
                return ResourceManager.GetString("miki_generic_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Information.
        /// </summary>
        internal static string miki_generic_global_information {
            get {
                return ResourceManager.GetString("miki_generic_global_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string miki_generic_information {
            get {
                return ResourceManager.GetString("miki_generic_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mekos.
        /// </summary>
        internal static string miki_generic_mekos {
            get {
                return ResourceManager.GetString("miki_generic_mekos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward.
        /// </summary>
        internal static string miki_generic_reward {
            get {
                return ResourceManager.GetString("miki_generic_reward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s global profile.
        /// </summary>
        internal static string miki_global_profile_user_header {
            get {
                return ResourceManager.GetString("miki_global_profile_user_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello! I am **Miki**! Use `&gt;help` to check out what I can do! :notes:.
        /// </summary>
        internal static string miki_join_message {
            get {
                return ResourceManager.GetString("miki_join_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        internal static string miki_label_prefix {
            get {
                return ResourceManager.GetString("miki_label_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s local profile.
        /// </summary>
        internal static string miki_local_profile_user_header {
            get {
                return ResourceManager.GetString("miki_local_profile_user_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have insufficient mekos..
        /// </summary>
        internal static string miki_mekos_insufficient {
            get {
                return ResourceManager.GetString("miki_mekos_insufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has divorced {1}.
        /// </summary>
        internal static string miki_module_accounts_divorce_content {
            get {
                return ResourceManager.GetString("miki_module_accounts_divorce_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔔 Divorce.
        /// </summary>
        internal static string miki_module_accounts_divorce_header {
            get {
                return ResourceManager.GetString("miki_module_accounts_divorce_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not married to this person!.
        /// </summary>
        internal static string miki_module_accounts_error_no_marriage {
            get {
                return ResourceManager.GetString("miki_module_accounts_error_no_marriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level: {0} ({1}/{2}).
        /// </summary>
        internal static string miki_module_accounts_information_level {
            get {
                return ResourceManager.GetString("miki_module_accounts_information_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank: #{0}.
        /// </summary>
        internal static string miki_module_accounts_information_rank {
            get {
                return ResourceManager.GetString("miki_module_accounts_information_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboards: Command usage.
        /// </summary>
        internal static string miki_module_accounts_leaderboards_commands_header {
            get {
                return ResourceManager.GetString("miki_module_accounts_leaderboards_commands_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboards: Global Experience.
        /// </summary>
        internal static string miki_module_accounts_leaderboards_header {
            get {
                return ResourceManager.GetString("miki_module_accounts_leaderboards_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboards: Local Experience.
        /// </summary>
        internal static string miki_module_accounts_leaderboards_local_header {
            get {
                return ResourceManager.GetString("miki_module_accounts_leaderboards_local_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboards: Mekos.
        /// </summary>
        internal static string miki_module_accounts_leaderboards_mekos_header {
            get {
                return ResourceManager.GetString("miki_module_accounts_leaderboards_mekos_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile {0} doesn&apos;t exist!.
        /// </summary>
        internal static string miki_module_accounts_profile_error_null {
            get {
                return ResourceManager.GetString("miki_module_accounts_profile_error_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Command.
        /// </summary>
        internal static string miki_module_accounts_profile_favourite_command {
            get {
                return ResourceManager.GetString("miki_module_accounts_profile_favourite_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to member since {0} | request took: {1}ms.
        /// </summary>
        internal static string miki_module_accounts_profile_footer {
            get {
                return ResourceManager.GetString("miki_module_accounts_profile_footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0]&apos;s Profile.
        /// </summary>
        internal static string miki_module_accounts_profile_header {
            get {
                return ResourceManager.GetString("miki_module_accounts_profile_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married to.
        /// </summary>
        internal static string miki_module_accounts_profile_marriedto {
            get {
                return ResourceManager.GetString("miki_module_accounts_profile_marriedto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile url.
        /// </summary>
        internal static string miki_module_accounts_profile_url {
            get {
                return ResourceManager.GetString("miki_module_accounts_profile_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled command `{0}`!.
        /// </summary>
        internal static string miki_module_admin_disable_command {
            get {
                return ResourceManager.GetString("miki_module_admin_disable_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled module `{0}`!.
        /// </summary>
        internal static string miki_module_admin_disable_module {
            get {
                return ResourceManager.GetString("miki_module_admin_disable_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled command `{0}`!.
        /// </summary>
        internal static string miki_module_admin_enable_command {
            get {
                return ResourceManager.GetString("miki_module_admin_enable_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled module `{0}`!.
        /// </summary>
        internal static string miki_module_admin_enable_module {
            get {
                return ResourceManager.GetString("miki_module_admin_enable_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module {0} is disabled..
        /// </summary>
        internal static string miki_module_admin_error_module_disabled {
            get {
                return ResourceManager.GetString("miki_module_admin_error_module_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💁 Kicked by.
        /// </summary>
        internal static string miki_module_admin_kick_by {
            get {
                return ResourceManager.GetString("miki_module_admin_kick_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been kicked from **{0}**!.
        /// </summary>
        internal static string miki_module_admin_kick_description {
            get {
                return ResourceManager.GetString("miki_module_admin_kick_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ KICK.
        /// </summary>
        internal static string miki_module_admin_kick_header {
            get {
                return ResourceManager.GetString("miki_module_admin_kick_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💬 Reason.
        /// </summary>
        internal static string miki_module_admin_kick_reason {
            get {
                return ResourceManager.GetString("miki_module_admin_kick_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot prune more than 100 messages per command..
        /// </summary>
        internal static string miki_module_admin_prune_error_max {
            get {
                return ResourceManager.GetString("miki_module_admin_prune_error_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I cannot delete messages in this channel. ):.
        /// </summary>
        internal static string miki_module_admin_prune_error_no_access {
            get {
                return ResourceManager.GetString("miki_module_admin_prune_error_no_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0} messages!.
        /// </summary>
        internal static string miki_module_admin_prune_success {
            get {
                return ResourceManager.GetString("miki_module_admin_prune_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Deleted your welcome message..
        /// </summary>
        internal static string miki_module_eventmessages_delete_guildjoin {
            get {
                return ResourceManager.GetString("miki_module_eventmessages_delete_guildjoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ New welcome message is set to: `{0}`.
        /// </summary>
        internal static string miki_module_eventmessages_set_guildjoin {
            get {
                return ResourceManager.GetString("miki_module_eventmessages_set_guildjoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t count on it..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_negative_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_negative_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My reply is no..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_negative_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_negative_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My sources say no..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_negative_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_negative_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook isn&apos;t good..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_negative_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_negative_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very doubtful..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_negative_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_negative_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply hazy, try again..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_neutral_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_neutral_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask again later..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_neutral_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_neutral_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Better not tell you now..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_neutral_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_neutral_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot predict now..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_neutral_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_neutral_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentrate and ask again..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_neutral_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_neutral_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is certain..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is decidedly so..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without a doubt..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, definitely..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may rely on it..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most likely..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_6 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook is good..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_7 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_8 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signs point to yes..
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_9 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎱 {0}, your question has been answered `{1}`.
        /// </summary>
        internal static string miki_module_fun_8ball_result {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the lower part of your lips.
        /// </summary>
        internal static string miki_module_fun_compliment_body_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the special angles your elbows make.
        /// </summary>
        internal static string miki_module_fun_compliment_body_10 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the dimples on your cheeks.
        /// </summary>
        internal static string miki_module_fun_compliment_body_11 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your smooth hair.
        /// </summary>
        internal static string miki_module_fun_compliment_body_12 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the smallest toe on your left foot.
        /// </summary>
        internal static string miki_module_fun_compliment_body_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the smallest toe on your right foot.
        /// </summary>
        internal static string miki_module_fun_compliment_body_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the second eyelash of your left eye.
        /// </summary>
        internal static string miki_module_fun_compliment_body_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the lower part of your chin.
        /// </summary>
        internal static string miki_module_fun_compliment_body_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the creepy finger on your left hand.
        /// </summary>
        internal static string miki_module_fun_compliment_body_6 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your cute smile.
        /// </summary>
        internal static string miki_module_fun_compliment_body_7 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to those dazzling eyes of yours.
        /// </summary>
        internal static string miki_module_fun_compliment_body_8 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the creepy finger on your right hand.
        /// </summary>
        internal static string miki_module_fun_compliment_body_9 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I like.
        /// </summary>
        internal static string miki_module_fun_compliment_prefix_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_prefix_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I love.
        /// </summary>
        internal static string miki_module_fun_compliment_prefix_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_prefix_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I admire.
        /// </summary>
        internal static string miki_module_fun_compliment_prefix_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_prefix_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I really enjoy.
        /// </summary>
        internal static string miki_module_fun_compliment_prefix_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_prefix_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For some reason, I like.
        /// </summary>
        internal static string miki_module_fun_compliment_prefix_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_prefix_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a lot..
        /// </summary>
        internal static string miki_module_fun_compliment_suffix_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_suffix_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a bit..
        /// </summary>
        internal static string miki_module_fun_compliment_suffix_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_suffix_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quite a bit..
        /// </summary>
        internal static string miki_module_fun_compliment_suffix_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_suffix_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a lot, is that weird?.
        /// </summary>
        internal static string miki_module_fun_compliment_suffix_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_suffix_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No images found on your search :(.
        /// </summary>
        internal static string miki_module_fun_image_error_no_image_found {
            get {
                return ResourceManager.GetString("miki_module_fun_image_error_no_image_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, I picked `{1}`.
        /// </summary>
        internal static string miki_module_fun_pick {
            get {
                return ResourceManager.GetString("miki_module_fun_pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve got nothing to pick from! :( Use commas (,) to split choices..
        /// </summary>
        internal static string miki_module_fun_pick_no_arg {
            get {
                return ResourceManager.GetString("miki_module_fun_pick_no_arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t believe I got fired from the calendar factory. All I did was take a day off..
        /// </summary>
        internal static string miki_module_fun_pun_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When I get naked in the bathroom, the shower usually gets turned on..
        /// </summary>
        internal static string miki_module_fun_pun_10 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thieves had broken into my house and stolen everything except my soap, shower gel, towels and deodorant. Dirty bastards..
        /// </summary>
        internal static string miki_module_fun_pun_11 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was Forrest Gump&apos;s email password? &apos;1forrest1&apos;.
        /// </summary>
        internal static string miki_module_fun_pun_12 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My first job was working in an orange juice factory, but I got canned - couldn&apos;t concentrate..
        /// </summary>
        internal static string miki_module_fun_pun_13 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m on a seafood diet. Every time I see food, I eat it..
        /// </summary>
        internal static string miki_module_fun_pun_14 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I wanna make a joke about sodium, but Na....
        /// </summary>
        internal static string miki_module_fun_pun_15 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why did the scientist install a knocker on his door? He wanted to win the No-bell prize!.
        /// </summary>
        internal static string miki_module_fun_pun_16 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A friend of mine tried to annoy me with bird puns, but I soon realized that toucan play at that game..
        /// </summary>
        internal static string miki_module_fun_pun_17 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having sex in an elevator is wrong on so many levels..
        /// </summary>
        internal static string miki_module_fun_pun_18 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I was going to give him a nasty look, but he already had one..
        /// </summary>
        internal static string miki_module_fun_pun_19 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How did I escape Iraq? Iran..
        /// </summary>
        internal static string miki_module_fun_pun_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A book just fell on my head. I&apos;ve only got my shelf to blame..
        /// </summary>
        internal static string miki_module_fun_pun_20 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do prisoners use to call each other? Cell phones..
        /// </summary>
        internal static string miki_module_fun_pun_21 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My math teacher called me average. How mean!.
        /// </summary>
        internal static string miki_module_fun_pun_22 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m no photographer, but I can picture us together..
        /// </summary>
        internal static string miki_module_fun_pun_23 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can you spot the blind guy at the nudist colony? It&apos;s not hard..
        /// </summary>
        internal static string miki_module_fun_pun_24 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atheism is a non-prophet organization..
        /// </summary>
        internal static string miki_module_fun_pun_25 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you call people who are afraid of Santa Claus? Claustrophobic..
        /// </summary>
        internal static string miki_module_fun_pun_26 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A hole was found in the wall of a nudist camp. The police are looking into it..
        /// </summary>
        internal static string miki_module_fun_pun_27 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which day do chickens hate the most? Friday..
        /// </summary>
        internal static string miki_module_fun_pun_28 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I hate insect puns, they really bug me..
        /// </summary>
        internal static string miki_module_fun_pun_29 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;d tell you a chemistry joke, but I know I wouldn&apos;t get a reaction..
        /// </summary>
        internal static string miki_module_fun_pun_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you hear about the Italian chef with a terminal illness? He pastaway..
        /// </summary>
        internal static string miki_module_fun_pun_30 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novice pirates make terrible singers because they can&apos;t hit the high seas..
        /// </summary>
        internal static string miki_module_fun_pun_31 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never discuss infinity with a mathematician, they can go on about it forever..
        /// </summary>
        internal static string miki_module_fun_pun_32 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I like European food, so I decided to Russia over there because I was Hungary. After Czech&apos;ing the menu I ordered Turkey. When I was Finnished I told the waiter &quot;Spain good but there is Norway I could eat another bite&quot;..
        /// </summary>
        internal static string miki_module_fun_pun_33 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What did the sushi say to the bee? Wasabee..
        /// </summary>
        internal static string miki_module_fun_pun_34 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t trust atoms, they make up everything..
        /// </summary>
        internal static string miki_module_fun_pun_35 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why was the parrot sent out of the classroom? Because he was using fowl language!.
        /// </summary>
        internal static string miki_module_fun_pun_36 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday I accidentally swallowed some food coloring. The doctor says I&apos;m OK, but I feel like I&apos;ve dyed a little inside..
        /// </summary>
        internal static string miki_module_fun_pun_37 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why don&apos;t programmers like nature? It has too many bugs..
        /// </summary>
        internal static string miki_module_fun_pun_38 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t quite remember how to throw a boomerang, but eventually it came back to me..
        /// </summary>
        internal static string miki_module_fun_pun_39 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I wasn&apos;t originally going to get a brain transplant, but then I changed my mind..
        /// </summary>
        internal static string miki_module_fun_pun_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When William joined the army he disliked the phrase &apos;fire at will&apos;..
        /// </summary>
        internal static string miki_module_fun_pun_40 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t trust stairs because they&apos;re always up to something..
        /// </summary>
        internal static string miki_module_fun_pun_41 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So what if I don&apos;t know what &quot;apocalypse&quot; means!? It&apos;s not the end of the world!.
        /// </summary>
        internal static string miki_module_fun_pun_42 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My friend&apos;s bakery burned down last night. Now his business is toast..
        /// </summary>
        internal static string miki_module_fun_pun_43 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Police were called to a daycare where a three-year-old was resisting a rest..
        /// </summary>
        internal static string miki_module_fun_pun_44 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peter Pan punched a lost boy into the sky last week. They say he&apos;ll Neverland..
        /// </summary>
        internal static string miki_module_fun_pun_45 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I did a theatrical performance about puns. Really, it was just a play on words..
        /// </summary>
        internal static string miki_module_fun_pun_46 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The other day I held the door open for a clown. I thought it was a nice jester..
        /// </summary>
        internal static string miki_module_fun_pun_47 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What did the grape say when it got stepped on? Nothing - but it let out a little whine..
        /// </summary>
        internal static string miki_module_fun_pun_48 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The girl quit her job at the doughnut factory because she was fed up with the hole business..
        /// </summary>
        internal static string miki_module_fun_pun_49 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m glad I know sign language, it&apos;s pretty handy..
        /// </summary>
        internal static string miki_module_fun_pun_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a sign on the lawn at a drug rehab center that said &quot;Keep off the grass&quot;..
        /// </summary>
        internal static string miki_module_fun_pun_50 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t have phone sex, you might get hearing aids..
        /// </summary>
        internal static string miki_module_fun_pun_51 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You and I are like the front and back ends of a book; we&apos;ll always end up back together..
        /// </summary>
        internal static string miki_module_fun_pun_52 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why was Cinderella thrown off the basketball team? She ran away from the ball..
        /// </summary>
        internal static string miki_module_fun_pun_6 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you hear about the guy who got hit in the head with a can of soda? He was lucky it was a soft drink..
        /// </summary>
        internal static string miki_module_fun_pun_7 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m reading a book about anti-gravity. It&apos;s impossible to put down..
        /// </summary>
        internal static string miki_module_fun_pun_8 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m emotionally constipated. I haven&apos;t given a shit in days..
        /// </summary>
        internal static string miki_module_fun_pun_9 {
            get {
                return ResourceManager.GetString("miki_module_fun_pun_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎲 {0} rolled a **{1}**..
        /// </summary>
        internal static string miki_module_fun_roll_result {
            get {
                return ResourceManager.GetString("miki_module_fun_roll_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And the winner of `{0}` is {1}..
        /// </summary>
        internal static string miki_module_fun_roulette_winner {
            get {
                return ResourceManager.GetString("miki_module_fun_roulette_winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And the winner is: {0}.
        /// </summary>
        internal static string miki_module_fun_roulette_winner_no_arg {
            get {
                return ResourceManager.GetString("miki_module_fun_roulette_winner_no_arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slots.
        /// </summary>
        internal static string miki_module_fun_slots_header {
            get {
                return ResourceManager.GetString("miki_module_fun_slots_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}🔸 has been added to your account..
        /// </summary>
        internal static string miki_module_fun_slots_win_amount {
            get {
                return ResourceManager.GetString("miki_module_fun_slots_win_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You win!.
        /// </summary>
        internal static string miki_module_fun_slots_win_header {
            get {
                return ResourceManager.GetString("miki_module_fun_slots_win_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I cannot do this kind of math!.
        /// </summary>
        internal static string miki_module_general_calc_error {
            get {
                return ResourceManager.GetString("miki_module_general_calc_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        internal static string miki_module_general_guildinfo_channels {
            get {
                return ResourceManager.GetString("miki_module_general_guildinfo_channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owned by.
        /// </summary>
        internal static string miki_module_general_guildinfo_owned_by {
            get {
                return ResourceManager.GetString("miki_module_general_guildinfo_owned_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string miki_module_general_guildinfo_roles {
            get {
                return ResourceManager.GetString("miki_module_general_guildinfo_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role count.
        /// </summary>
        internal static string miki_module_general_guildinfo_roles_count {
            get {
                return ResourceManager.GetString("miki_module_general_guildinfo_roles_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string miki_module_general_guildinfo_users {
            get {
                return ResourceManager.GetString("miki_module_general_guildinfo_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Channels.
        /// </summary>
        internal static string miki_module_general_guildinfo_voicechannels {
            get {
                return ResourceManager.GetString("miki_module_general_guildinfo_voicechannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases.
        /// </summary>
        internal static string miki_module_general_help_aliases {
            get {
                return ResourceManager.GetString("miki_module_general_help_aliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string miki_module_general_help_description {
            get {
                return ResourceManager.GetString("miki_module_general_help_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A personal message with all my commands is on the way! Use `&gt;help [command]` for more information about specific commands!.
        /// </summary>
        internal static string miki_module_general_help_dm {
            get {
                return ResourceManager.GetString("miki_module_general_help_dm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string miki_module_general_help_usage {
            get {
                return ResourceManager.GetString("miki_module_general_help_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        internal static string miki_module_general_info_docs {
            get {
                return ResourceManager.GetString("miki_module_general_info_docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi everyone! I have created a Patreon to allow people to support Miki. Please check it out and support if you can!.
        /// </summary>
        internal static string miki_module_general_info_donate_string {
            get {
                return ResourceManager.GetString("miki_module_general_info_donate_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string miki_module_general_info_links {
            get {
                return ResourceManager.GetString("miki_module_general_info_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks to: Florestina, Mei, Rappy, Rie, Rosie.
        /// </summary>
        internal static string miki_module_general_info_made_by_description {
            get {
                return ResourceManager.GetString("miki_module_general_info_made_by_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Made by:** Veld.
        /// </summary>
        internal static string miki_module_general_info_made_by_header {
            get {
                return ResourceManager.GetString("miki_module_general_info_made_by_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to patreon.
        /// </summary>
        internal static string miki_module_general_info_patreon {
            get {
                return ResourceManager.GetString("miki_module_general_info_patreon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subreddit.
        /// </summary>
        internal static string miki_module_general_info_reddit {
            get {
                return ResourceManager.GetString("miki_module_general_info_reddit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support server.
        /// </summary>
        internal static string miki_module_general_info_server {
            get {
                return ResourceManager.GetString("miki_module_general_info_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twitter.
        /// </summary>
        internal static string miki_module_general_info_twitter {
            get {
                return ResourceManager.GetString("miki_module_general_info_twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to website.
        /// </summary>
        internal static string miki_module_general_info_website {
            get {
                return ResourceManager.GetString("miki_module_general_info_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you go! :3.
        /// </summary>
        internal static string miki_module_general_invite_dm {
            get {
                return ResourceManager.GetString("miki_module_general_invite_dm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ll send you a private message with an invite URL..
        /// </summary>
        internal static string miki_module_general_invite_message {
            get {
                return ResourceManager.GetString("miki_module_general_invite_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set your prefix to nothing. Please consult `&gt;help prefix` to find out what it does..
        /// </summary>
        internal static string miki_module_general_prefix_error_no_arg {
            get {
                return ResourceManager.GetString("miki_module_general_prefix_error_no_arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example Command.
        /// </summary>
        internal static string miki_module_general_prefix_example_command_header {
            get {
                return ResourceManager.GetString("miki_module_general_prefix_example_command_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current prefix is **{0}**!.
        /// </summary>
        internal static string miki_module_general_prefix_help {
            get {
                return ResourceManager.GetString("miki_module_general_prefix_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        internal static string miki_module_general_prefix_help_header {
            get {
                return ResourceManager.GetString("miki_module_general_prefix_help_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙️ Changed prefix!.
        /// </summary>
        internal static string miki_module_general_prefix_success_header {
            get {
                return ResourceManager.GetString("miki_module_general_prefix_success_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed your prefix to **{0}**!.
        /// </summary>
        internal static string miki_module_general_prefix_success_message {
            get {
                return ResourceManager.GetString("miki_module_general_prefix_success_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by {0}.
        /// </summary>
        internal static string miki_module_general_urban_author {
            get {
                return ResourceManager.GetString("miki_module_general_urban_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition.
        /// </summary>
        internal static string miki_module_general_urban_definition {
            get {
                return ResourceManager.GetString("miki_module_general_urban_definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        internal static string miki_module_general_urban_example {
            get {
                return ResourceManager.GetString("miki_module_general_urban_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string miki_module_general_urban_rating {
            get {
                return ResourceManager.GetString("miki_module_general_urban_rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you mean?.
        /// </summary>
        internal static string miki_module_help_didyoumean {
            get {
                return ResourceManager.GetString("miki_module_help_didyoumean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not found..
        /// </summary>
        internal static string miki_module_help_error_null_header {
            get {
                return ResourceManager.GetString("miki_module_help_error_null_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a command. To use `{0}help [command]` please fill in a existing command!.
        /// </summary>
        internal static string miki_module_help_error_null_message {
            get {
                return ResourceManager.GetString("miki_module_help_error_null_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This pasta already exists! Try a different name..
        /// </summary>
        internal static string miki_module_pasta_create_error_already_exist {
            get {
                return ResourceManager.GetString("miki_module_pasta_create_error_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created pasta `{0}`!.
        /// </summary>
        internal static string miki_module_pasta_create_success {
            get {
                return ResourceManager.GetString("miki_module_pasta_create_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted pasta `{0}`!.
        /// </summary>
        internal static string miki_module_pasta_delete_success {
            get {
                return ResourceManager.GetString("miki_module_pasta_delete_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited `{0}`!.
        /// </summary>
        internal static string miki_module_pasta_edit_success {
            get {
                return ResourceManager.GetString("miki_module_pasta_edit_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot {0} pastas you did not create!.
        /// </summary>
        internal static string miki_module_pasta_error_no_permissions {
            get {
                return ResourceManager.GetString("miki_module_pasta_error_no_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This pasta doesn&apos;t exist!.
        /// </summary>
        internal static string miki_module_pasta_error_null {
            get {
                return ResourceManager.GetString("miki_module_pasta_error_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter one of the tags or commands..
        /// </summary>
        internal static string miki_module_pasta_error_search_no_arg {
            get {
                return ResourceManager.GetString("miki_module_pasta_error_search_no_arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search query found. Please specify what you want to search for..
        /// </summary>
        internal static string miki_module_pasta_error_search_no_results {
            get {
                return ResourceManager.GetString("miki_module_pasta_error_search_no_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify which pasta you would like to {0}..
        /// </summary>
        internal static string miki_module_pasta_error_specify {
            get {
                return ResourceManager.GetString("miki_module_pasta_error_specify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check.
        /// </summary>
        internal static string miki_module_pasta_error_specify_check {
            get {
                return ResourceManager.GetString("miki_module_pasta_error_specify_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        internal static string miki_module_pasta_error_specify_delete {
            get {
                return ResourceManager.GetString("miki_module_pasta_error_specify_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        internal static string miki_module_pasta_error_specify_edit {
            get {
                return ResourceManager.GetString("miki_module_pasta_error_specify_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upvote.
        /// </summary>
        internal static string miki_module_pasta_error_specify_upvote {
            get {
                return ResourceManager.GetString("miki_module_pasta_error_specify_upvote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string miki_module_pasta_identify_created_by {
            get {
                return ResourceManager.GetString("miki_module_pasta_identify_created_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        internal static string miki_module_pasta_identify_date_created {
            get {
                return ResourceManager.GetString("miki_module_pasta_identify_date_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string miki_module_pasta_identify_rating {
            get {
                return ResourceManager.GetString("miki_module_pasta_identify_rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times used.
        /// </summary>
        internal static string miki_module_pasta_identify_times_used {
            get {
                return ResourceManager.GetString("miki_module_pasta_identify_times_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but you haven&apos;t created any pastas yet..
        /// </summary>
        internal static string miki_module_pasta_mine_error_null {
            get {
                return ResourceManager.GetString("miki_module_pasta_mine_error_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s pastas.
        /// </summary>
        internal static string miki_module_pasta_mine_header {
            get {
                return ResourceManager.GetString("miki_module_pasta_mine_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but we couldn&apos;t find a pasta with `{0}`.
        /// </summary>
        internal static string miki_module_pasta_search_error_no_results {
            get {
                return ResourceManager.GetString("miki_module_pasta_search_error_no_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page {0} of {1}.
        /// </summary>
        internal static string miki_module_pasta_search_footer {
            get {
                return ResourceManager.GetString("miki_module_pasta_search_footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔎 I found these pastas:.
        /// </summary>
        internal static string miki_module_pasta_search_header {
            get {
                return ResourceManager.GetString("miki_module_pasta_search_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your vote has been updated! Current Score: `{0}`.
        /// </summary>
        internal static string miki_module_pasta_vote_success {
            get {
                return ResourceManager.GetString("miki_module_pasta_vote_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} direct messages.
        /// </summary>
        internal static string miki_module_settings_dm {
            get {
                return ResourceManager.GetString("miki_module_settings_dm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} error notifications.
        /// </summary>
        internal static string miki_module_settings_error_dm {
            get {
                return ResourceManager.GetString("miki_module_settings_error_dm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} guild notifications.
        /// </summary>
        internal static string miki_module_settings_guild_notifications {
            get {
                return ResourceManager.GetString("miki_module_settings_guild_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who is {0}!?.
        /// </summary>
        internal static string miki_module_whois_header {
            get {
                return ResourceManager.GetString("miki_module_whois_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🙎 Personal.
        /// </summary>
        internal static string miki_module_whois_tag_personal {
            get {
                return ResourceManager.GetString("miki_module_whois_tag_personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none (yet!).
        /// </summary>
        internal static string miki_placeholder_null {
            get {
                return ResourceManager.GetString("miki_placeholder_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string miki_success_message_generic {
            get {
                return ResourceManager.GetString("miki_success_message_generic", resourceCulture);
            }
        }
    }
}
