//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miki.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class hi_HI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal hi_HI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Miki.Languages.hi-HI", typeof(hi_HI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अज्ञात एरर!.
        /// </summary>
        internal static string miki_error_message_generic {
            get {
                return ResourceManager.GetString("miki_error_message_generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miki के कोड में गड़बड़ी के कारण आपके सवाल का जवाब देने में असमर्थ। हम आपको प्राइवेट संदेश के ज़रिए निर्देश देंगे।.
        /// </summary>
        internal static string miki_errors_enabled_message {
            get {
                return ResourceManager.GetString("miki_errors_enabled_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} की ग्लोबल प्रोफ़ाइल.
        /// </summary>
        internal static string miki_global_profile_user_header {
            get {
                return ResourceManager.GetString("miki_global_profile_user_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नमस्ते! मेरा नाम **Miki** है! `help` का इस्तेमाल करें और जानें मेरे फीचर्स! :notes:.
        /// </summary>
        internal static string miki_join_message {
            get {
                return ResourceManager.GetString("miki_join_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} की लोकल प्रोफ़ाइल.
        /// </summary>
        internal static string miki_local_profile_user_header {
            get {
                return ResourceManager.GetString("miki_local_profile_user_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आपके पास पर्याप्त mekos नहीं है।.
        /// </summary>
        internal static string miki_mekos_insufficient {
            get {
                return ResourceManager.GetString("miki_mekos_insufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ आपका वेलकम संदेश डिलीट कर दिया गया है।.
        /// </summary>
        internal static string miki_module_eventmessages_delete_guildjoin {
            get {
                return ResourceManager.GetString("miki_module_eventmessages_delete_guildjoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ आपका नया वेलकम संदेश यह है: `{0}` .
        /// </summary>
        internal static string miki_module_eventmessages_set_guildjoin {
            get {
                return ResourceManager.GetString("miki_module_eventmessages_set_guildjoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शायद नहीं।.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_negative_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_negative_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मेरा जवाब ना है।.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_negative_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_negative_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मेरे सूत्र ना कह रहे हैं।.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_negative_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_negative_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दृष्टिकोण सही नहीं है।.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_negative_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_negative_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बहुत संदेहजनक।.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_negative_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_negative_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अस्पष्ट रिप्लाई, कृपया पुनः कोशिश करें।.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_neutral_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_neutral_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to थोड़ी देर बाद पुनः पूछें।.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_neutral_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_neutral_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अभी बताने के मूड में नहीं हूं।.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_neutral_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_neutral_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कुछ कह नहीं सकता।.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_neutral_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_neutral_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ध्यान से पुनः कोशिश करें।.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_neutral_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_neutral_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्वाभाविक है।.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to निश्चित रूप से।.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बेशक।.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to हां बिलकुल.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कहा जा सकता है।.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to संभव है।.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_6 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दृषटिकोण सही है।.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_7 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to हां।.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_8 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to इशारा हां की तरफ है।.
        /// </summary>
        internal static string miki_module_fun_8ball_answer_positive_9 {
            get {
                return ResourceManager.GetString("miki_module_fun_8ball_answer_positive_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आपके होंठ.
        /// </summary>
        internal static string miki_module_fun_compliment_body_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आपके हाथों का अजीब आकार.
        /// </summary>
        internal static string miki_module_fun_compliment_body_10 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आपके डिम्पल वाले गाल.
        /// </summary>
        internal static string miki_module_fun_compliment_body_11 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आपके रेशमी बाल.
        /// </summary>
        internal static string miki_module_fun_compliment_body_12 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आपके बाएं पैर की सबसे छोटी वली उंगली.
        /// </summary>
        internal static string miki_module_fun_compliment_body_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आपके दाएं पैर की सबसे छोटी वली उंगली.
        /// </summary>
        internal static string miki_module_fun_compliment_body_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आपकी बाएं आंख की पलकें.
        /// </summary>
        internal static string miki_module_fun_compliment_body_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string miki_module_fun_compliment_body_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आपके बाएं आंख की अजीब सी उंगली.
        /// </summary>
        internal static string miki_module_fun_compliment_body_6 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आपकी प्यारी मुस्कान.
        /// </summary>
        internal static string miki_module_fun_compliment_body_7 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आपकी वो चमकीली आंखें.
        /// </summary>
        internal static string miki_module_fun_compliment_body_8 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आपके दाएं आंख की अजीब सी उंगली.
        /// </summary>
        internal static string miki_module_fun_compliment_body_9 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_body_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मुझे पसंद है.
        /// </summary>
        internal static string miki_module_fun_compliment_prefix_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_prefix_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मुझे प्यार है.
        /// </summary>
        internal static string miki_module_fun_compliment_prefix_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_prefix_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मुझे पसंद है.
        /// </summary>
        internal static string miki_module_fun_compliment_prefix_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_prefix_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मुझे सच में पसंद है.
        /// </summary>
        internal static string miki_module_fun_compliment_prefix_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_prefix_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पता नही क्यों, मुझे पसंद है.
        /// </summary>
        internal static string miki_module_fun_compliment_prefix_5 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_prefix_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बहुत ज़्यादा।.
        /// </summary>
        internal static string miki_module_fun_compliment_suffix_1 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_suffix_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कुछ कुछ।.
        /// </summary>
        internal static string miki_module_fun_compliment_suffix_2 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_suffix_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to थोड़ा सा।.
        /// </summary>
        internal static string miki_module_fun_compliment_suffix_3 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_suffix_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बोहोत ज़्यादा, क्या यह अजीब तो नहीं?.
        /// </summary>
        internal static string miki_module_fun_compliment_suffix_4 {
            get {
                return ResourceManager.GetString("miki_module_fun_compliment_suffix_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, में `{1}` चुनता हूं.
        /// </summary>
        internal static string miki_module_fun_pick {
            get {
                return ResourceManager.GetString("miki_module_fun_pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मेरे पास चुनने के लिए कुछ नहीं है! :( विकल्पों को कॉमा (,) के ज़रिए अलग करें।.
        /// </summary>
        internal static string miki_module_fun_pick_no_arg {
            get {
                return ResourceManager.GetString("miki_module_fun_pick_no_arg", resourceCulture);
            }
        }
    }
}
