namespace Miki.Modules.Overwatch.Objects
{
    public class OverwatchGameStats
    {
        public double healing_done_avg_per_10_min { get; set; }
        public double eliminations { get; set; }
        public double solo_kills_avg_per_10_min { get; set; }
        public double all_damage_done_avg_per_10_min { get; set; }
        public double medals_bronze { get; set; }
        public double final_blows_most_in_game { get; set; }
        public float objective_time { get; set; }
        public double time_spent_on_fire { get; set; }
        public double melee_final_blows { get; set; }
        public double all_damage_done { get; set; }
        public double recon_assists { get; set; }
        public double medals { get; set; }
        public double objective_kills { get; set; }
        public double hero_damage_done_avg_per_10_min { get; set; }
        public double defensive_assists_most_in_game { get; set; }
        public double environmental_kills { get; set; }
        public double hero_damage_done { get; set; }
        public double solo_kills { get; set; }
        public double melee_final_blows_most_in_game { get; set; }
        public double multikill_best { get; set; }
        public double objective_kills_most_in_game { get; set; }
        public double objective_time_most_in_game { get; set; }
        public double objective_time_avg_per_10_min { get; set; }
        public double defensive_assists { get; set; }
        public double ultimates_earned { get; set; }
        public double environmental_deaths { get; set; }
        public double multikills { get; set; }
        public double time_holding_ultimate { get; set; }
        public double barrier_damage_done { get; set; }
        public double deaths { get; set; }
        public double melee_final_blows_avg_per_10_min { get; set; }
        public double recon_assists_most_in_game { get; set; }
        public double kpd { get; set; }
        public double all_damage_done_most_in_game { get; set; }
        public double games_won { get; set; }
        public double offensive_assists_most_in_game { get; set; }
        public double time_spent_on_fire_most_in_game { get; set; }
        public double environmental_kill_most_in_game { get; set; }
        public double healing_done_most_in_game { get; set; }
        public double kill_streak_best { get; set; }
        public double final_blows { get; set; }
        public double cards { get; set; }
        public double damage_blocked { get; set; }
        public double medals_silver { get; set; }
        public double turrets_destroyed { get; set; }
        public double barrier_damage_done_avg_per_10_min { get; set; }
        public double healing_done { get; set; }
        public double medals_gold { get; set; }
        public double time_spent_on_fire_avg_per_10_min { get; set; }
        public double eliminations_most_in_game { get; set; }
        public double final_blows_avg_per_10_min { get; set; }
        public double ultimates_used { get; set; }
        public double of_match_on_fire { get; set; }
        public double shots_fired { get; set; }
        public double turrets_destroyed_most_in_game { get; set; }
        public double melee_percentage_of_final_blows { get; set; }
        public double time_played { get; set; }
        public double hero_damage_done_most_in_game { get; set; }
        public double objective_kills_avg_per_10_min { get; set; }
        public double deaths_avg_per_10_min { get; set; }
        public double eliminations_avg_per_10_min { get; set; }
        public double offensive_assists { get; set; }
        public double weapon_accuracy { get; set; }
        public double solo_kills_most_in_game { get; set; }
    }
}